name:                scarch
version:             0.1.0.0
#synopsis:
#description:
homepage:            https://github.com/unknownloner/scarch#readme
license:             BSD3
author:              Galen Alderson
maintainer:          galen.alderson@gmail.com
copyright:           2017 Galen Alderson
category:            Web
extra-source-files:
- README.md

dependencies:
  - base >= 4.7 && < 5
  - aeson
  - ansi-wl-pprint
  - async
  - bytestring
  - conduit-combinators
  - directory
  - filepath
  - free
  - http-conduit
  - optparse-applicative
  - process
  - stm

executables:
  scarch:
    source-dirs:      src
    main:             Main.hs
    ghc-options:
    - -rtsopts
    - -threaded
    - -with-rtsopts=-N
    - -Wall
